socks5server/__init__.py,sha256=1ZS9JX_v-FTHxki73YeAJOCdzRw7HkqRAMvl8FWkzGA,179
socks5server/__main__.py,sha256=m-z89E_MEQwZY_Wu0Hb3NNxzPJyCQX16r7dt3bsnmvs,1473
socks5server/auth.py,sha256=NNN0CQ2DcitSSGnvZPfX_94MFwRPJP3n6t6uglgUFZg,1102
socks5server/client_socks5.py,sha256=0c42sr9lAGLE9LT3o0TnbPw_JoCs-p8bZ4IeIDTlP1E,3642
socks5server/exceptions.py,sha256=XZ4rZ14GF8kKazYYiUJ7ySpQ2q3S-smpwLJ_OmYDJvQ,41
socks5server/relay.py,sha256=Yxj9v3F_dJ1LKicuX6FsPZQLoJww58mzUZz0KuUs8CI,1888
socks5server/server.py,sha256=oBnN7vGWqhO3-pAbwtALxp-T6JrxQzHCpBVeogzEdqE,2749
pysocks5server-0.1.0.dist-info/LICENSE,sha256=s0fvkDDUlyC82Nd9R2zqexEZRh-AfOCcc6WIMFVpFL0,1064
pysocks5server-0.1.0.dist-info/METADATA,sha256=lbkr63wpQ_j9IXK5WUD_qP5iWLrnIH6B7qdKyo8d1gA,3557
pysocks5server-0.1.0.dist-info/WHEEL,sha256=Zb28QaM1gQi8f4VCBhsUklF61CTlNYfs9YAZn-TOGFk,88
pysocks5server-0.1.0.dist-info/RECORD,,
